title: John Smith Photography Collection
email: archive@example.com
description: >-
  Digital repository for the John Smith Photography Collection, featuring street photography,
  portraits, and documentary work from 1950-1990.
baseurl: "/digital-archives-repository"
url: "https://wongsyvr.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  fonds:
    output: true
    permalink: /fonds/:path/
  series:
    output: true
    permalink: /series/:path/
  files:
    output: true
    permalink: /files/:path/
  items:
    output: true
    permalink: /items/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "fonds"
    values:
      layout: "fonds"
  - scope:
      path: ""
      type: "series"
    values:
      layout: "series"
  - scope:
      path: ""
      type: "files"
    values:
      layout: "file"
  - scope:
      path: ""
      type: "items"
    values:
      layout: "item"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .gitignore
