title: Digital Archives Repository
email: your-email@example.com
description: >-
  A digital repository for archival materials following RAD standards.
baseurl: "/digital-archives-repository" # the subpath of your site, e.g. /blog
url: "https://wongsyvr.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  fonds:
    output: true
    permalink: /fonds/:path/
  series:
    output: true
    permalink: /series/:path/
  files:
    output: true
    permalink: /files/:path/
  items:
    output: true
    permalink: /items/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "fonds"
    values:
      layout: "fonds"
  - scope:
      path: ""
      type: "series"
    values:
      layout: "series"
  - scope:
      path: ""
      type: "files"
    values:
      layout: "file"
  - scope:
      path: ""
      type: "items"
    values:
      layout: "item"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .gitignore
