title: John Smith Photography Collection
email: archive@example.com
description: >-
  Digital repository for the John Smith Photography Collection, featuring street photography,
  portraits, and documentary work from 1950-1990.
baseurl: "/digital-archives-repository"
url: "https://wongsyvr.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  fonds:
    output: true
    permalink: /fonds/:path/
  series:
    output: true
    permalink: /series/:path/
  files:
    output: true
    permalink: /files/:path/

# Collection defaults
defaults:
  - scope:
      path: ""
      type: "fonds"
    values:
      layout: "fonds"
  - scope:
      path: ""
      type: "series"
    values:
      layout: "series"
  - scope:
      path: ""
      type: "files"
    values:
      layout: "file"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - README.md
